---

- name: Disable remote root login
  lineinfile:
    dest: "{{ sshd_config }}"
    regexp: "^#?PermitEmptyPasswords"
    line: PermitEmptyPasswords no"

- name: Disable password login
  lineinfile:
    dest: "{{ sshd_config }}"
    regexp: "^#?PasswordAuthentication "
    line: "PasswordAuthentication no"

- name: Disable empty password login
  lineinfile:
    dest: "{{ sshd_config }}"
    regexp: "^#?PasswordAuthentication "
    line: "PasswordAuthentication no"

- name: Restart ssh
  systemd:
    name: ssh
    state: restarted
