---
- name: Create directory for dynamic inventory
  file:
    path: $HOME/dynamic_inventory
    state: directory
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0700

- name: Copy dynamic inventory file
  copy:
    src: dynamic_inventory.py
    dest: "{{ ansible_env.HOME }}/dynamic_inventory/dynamic_inventory.py"
    mode: 0700
